rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: jruby
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
  - bundle --version